### ISSUE TITLE
Error with Bubble plot when comparing WGCNA objects

### ISSUE THREAD

**Issue by Lachiemckbioinfo** [mortazavilab/PyWGCNA#108]
Hi,
This program is working great so far for me now, thanks. I've just come up with an issue when comparing multiple WGCNA objects with the bubble plot. I get an error with generating the bubble plot colorbar. My first attempt was with 5 WGCNA objects, so I tried again with three in case that was an issue, but the error repeated just the same. The error output is below:

## Error output
Traceback (most recent call last):
  File "/home/ubuntu/PyWGCNA/AtaSC/split/combined/WGCNA_comparison.py", line 128, in <module>
    plot_3ways()
  File "/home/ubuntu/PyWGCNA/AtaSC/split/combined/WGCNA_comparison.py", line 110, in plot_3ways
    comparison_3.plotBubbleComparison(color=color,
  File "/home/ubuntu/PyWGCNA/venv/lib/python3.10/site-packages/PyWGCNA/comparison.py", line 444, in plotBubbleComparison
    ax.figure.colorbar(sm, shrink=0.25, label='-log10(P_value)')
  File "/home/ubuntu/PyWGCNA/venv/lib/python3.10/site-packages/matplotlib/figure.py", line 1285, in colorbar
    raise ValueError(
ValueError: Unable to determine Axes to steal space for Colorbar. Either provide the *cax* argument to use as the Axes for the Colorbar, provide the *ax* argument to steal space from it, or add *mappable* to an Axes.

## Code snippet
```python
import PyWGCNA
import os
import pandas as pd 

dir = 'data'
outdir = 'output_5ways'
#outdir_3 = 'output_3ways'
outdir_3 = 'test'

# Add function for custom printing with linebreaks. Just for making debugging pretty.
def customprint(*args):
    linebreak = "\n------------------------------\n"
    print(f"{linebreak}")
    for arg in args:
        print(arg)
    print(f"{linebreak}")

# Read PyWGCNA files. Make sure you have the correct names, stupid.
# Note: Kept having keyerror later with lowercase names. Use uppercase for first letter of var names.
Culturing = PyWGCNA.readWGCNA(os.path.join(dir, 'Culturing.p'))
Density = PyWGCNA.readWGCNA(os.path.join(dir, 'Density.p'))
Light = PyWGCNA.readWGCNA(os.path.join(dir, 'Light.p'))
Nutrient = PyWGCNA.readWGCNA(os.path.join(dir, 'Nutrient.p'))
Temperature = PyWGCNA.readWGCNA(os.path.join(dir, 'Temperature.p'))

# Apparently it's this easy.
comparison = PyWGCNA.compareNetworks(PyWGCNAs = [Culturing, Density, Light, Nutrient, Temperature])

comparison_3 = PyWGCNA.compareNetworks(PyWGCNAs = [Culturing, Light, Density])

# Calculate statistics dataframes
# All 5
jaccard = comparison.jaccard_similarity
fraction = comparison.fraction
pvalue = comparison.P_value

# Just 3
jaccard_3 = comparison_3.jaccard_similarity
fraction_3 = comparison_3.fraction
pvalue_3 = comparison_3.P_value


# Save stats to csv files
def data_to_csv(data, folder, outname):
    outfile = os.path.join(folder, outname)
    data.to_csv(outfile)
    
def data_5ways():
    data_to_csv(jaccard, outdir, 'jaccard_similarity.csv')
    data_to_csv(fraction, outdir, 'fraction_comparison.csv')
    data_to_csv(pvalue, outdir, 'p_value.csv')
    customprint(f'Saved stats data (5 ways) to files')

def data_3ways():
    data_to_csv(jaccard, outdir_3, 'jaccard_similarity.csv')
    data_to_csv(fraction, outdir_3, 'fraction_comparison.csv')
    data_to_csv(pvalue, outdir_3, 'p_value.csv')
    customprint(f'Saved stats data (3 ways) to files')




# PLOT ALL THE DATA
# Coloring based on this:
"""pyw.setMetadataColor('Test', {'Culturing': 'green',
                            'Temperature': 'red',
                            'Density': 'purple',
                            'Light': 'gold',
                            'Nutrient': 'chocolate'})"""

color = {'Culturing': 'lightgreen',
         'Density': 'violet',
         'Light': 'lightgoldenrodyellow',
         'Nutrient': 'sandybrown',
         'Temperature': 'lightcoral'} #Lightred isn't a CSS or MatPlotLib colour
def plot_5ways():
    # Who's Jaccard?
    comparison.plotJaccardSimilarity(color=color,
                                    cutoff=0.2,
                                    plot_format='pdf',
                                    file_name=os.path.join(outdir, 'jaccard_similarity_5ways'))

    # That's hot
    comparison.plotHeatmapComparison(plot_format='pdf',
                                    file_name = os.path.join(outdir, 'heatmap_comparison_5ways'))


    # BUBBLES!
    try:
        comparison.plotBubbleComparison(color=color,
                                        plot_format='pdf',
                                        file_name = os.path.join(outdir, 'bubble_comparison_5ways'))
    except Exception as error:
        customprint(f"Bubble comparison (5ways) failed")
        print(type(error).__name__, "-", error)



def plot_3ways():
    # Who's Jaccard?
    comparison_3.plotJaccardSimilarity(color=color,
                                    cutoff=0.2,
                                    plot_format='pdf',
                                    file_name=os.path.join(outdir_3, 'jaccard_similarity_3ways'))

    # That's hot
    comparison_3.plotHeatmapComparison(plot_format='pdf',
                                    file_name = os.path.join(outdir_3, 'heatmap_comparison_3ways'))
    
    # BUBBLES!
    comparison_3.plotBubbleComparison(color=color,
                                        plot_format='pdf',
                                        file_name = os.path.join(outdir_3, 'bubble_comparison_3ways'))



#data_5ways()
data_3ways()

#plot_5ways()
plot_3ways()

# Best to plot in separate runs. I found that doing plotting one after the other screwed with the PDF sizing (though test n=1, so maybe idk)

# Save the comparison
#comparison.saveComparison(name="comparison_results_5ways")
#comparison_3.saveComparison(name="comparison_results_3ways")
# Can be read with comparison = PyWGCNA.readComparison('comparison_results_5ways)
```

Thank you,
Lachlan

**Comment by nargesr** [comment]
Hi @Lachiemckbioinfo

I updated the function to be compatible with the latest version of matplotlib.

I will release a new version soon and keep you posted

Thank you for your help.

**Comment by nargesr** [comment]
Hi @Lachiemckbioinfo 

Please install the latest version and let me know if you encounter any issues.

**Comment by Lachiemckbioinfo** [comment]
Thank you, that works well now. 

Best,
Lachlan
