### ISSUE TITLE
Issues running test.py

### ISSUE THREAD

**Issue by yashsondhi** [mortazavilab/PyWGCNA#2]
Error log: I am tryoin gtho run the test.py scri[t in the tutorial and am getting the following error. 
Saving data to be True, checking requirements ...
Pre-processing...
        Detecting genes and samples with too many missing values...
Traceback (most recent call last):
  File "/Users/yashsondhi/opt/anaconda3/envs/bioinfo/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3653, in _dendrogram_calculate_info
    _dendrogram_calculate_info(
  File "/Users/yashsondhi/opt/anaconda3/envs/bioinfo/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3653, in _dendrogram_calculate_info
    _dendrogram_calculate_info(
  File "/Users/yashsondhi/opt/anaconda3/envs/bioinfo/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3653, in _dendrogram_calculate_info
    _dendrogram_calculate_info(
  [Previous line repeated 992 more times]
  File "/Users/yashsondhi/opt/anaconda3/envs/bioinfo/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3620, in _dendrogram_calculate_info
    _dendrogram_calculate_info(
  File "/Users/yashsondhi/opt/anaconda3/envs/bioinfo/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3550, in _dendrogram_calculate_info
    _append_singleton_leaf_node(Z, p, n, level, lvs, ivl,
  File "/Users/yashsondhi/opt/anaconda3/envs/bioinfo/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3422, in _append_singleton_leaf_node
    ivl.append(labels[int(i - n)])
  File "/Users/yashsondhi/opt/anaconda3/envs/bioinfo/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5038, in __getitem__
    key = com.cast_scalar_indexer(key, warn_float=True)
  File "/Users/yashsondhi/opt/anaconda3/envs/bioinfo/lib/python3.9/site-packages/pandas/core/common.py", line 175, in cast_scalar_indexer
    if lib.is_float(val) and val.is_integer():
RecursionError: maximum recursion depth exceeded while calling a Python object
(bioinfo) yashsondhi@Yashs-MBP tutorials % python test.py
Saving data to be True, checking requirements ...
Pre-processing...
        Detecting genes and samples with too many missing values...
Traceback (most recent call last):
  File "/Users/yashsondhi/opt/anaconda3/envs/bioinfo/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3653, in _dendrogram_calculate_info
    _dendrogram_calculate_info(
  File "/Users/yashsondhi/opt/anaconda3/envs/bioinfo/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3653, in _dendrogram_calculate_info
    _dendrogram_calculate_info(
  File "/Users/yashsondhi/opt/anaconda3/envs/bioinfo/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3653, in _dendrogram_calculate_info
    _dendrogram_calculate_info(
  [Previous line repeated 992 more times]
  File "/Users/yashsondhi/opt/anaconda3/envs/bioinfo/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3620, in _dendrogram_calculate_info
    _dendrogram_calculate_info(
  File "/Users/yashsondhi/opt/anaconda3/envs/bioinfo/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3550, in _dendrogram_calculate_info
    _append_singleton_leaf_node(Z, p, n, level, lvs, ivl,
  File "/Users/yashsondhi/opt/anaconda3/envs/bioinfo/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3422, in _append_singleton_leaf_node
    ivl.append(labels[int(i - n)])
  File "/Users/yashsondhi/opt/anaconda3/envs/bioinfo/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5038, in __getitem__
    key = com.cast_scalar_indexer(key, warn_float=True)
  File "/Users/yashsondhi/opt/anaconda3/envs/bioinfo/lib/python3.9/site-packages/pandas/core/common.py", line 175, in cast_scalar_indexer
    if lib.is_float(val) and val.is_integer():
RecursionError: maximum recursion depth exceeded while calling a Python object
(bioinfo) yashsondhi@Yashs-MBP tutorials % conda deactivate

**Comment by nargesr** [comment]
I suggest you follow `Quick_Start.ipynb` on the test data. To make sure your data is inserted in PyWGCNA correctly, try to look at `pyWGCNA_5xFAD.geneExpr.to_df()` to make sure your gene_ids are stored as an index and your sample names are stored as a columns.

**Comment by nargesr** [comment]
Hi again,

Can you please check that you have the latest version of [the input files](https://github.com/mortazavilab/PyWGCNA/blob/main/tutorials/5xFAD_paper.zip), as well?

Unfotunelty, I can not reproduce your error but if you can tell me which version of anndata you used it might be helpful

**Comment by 1391794753** [comment]
I got a same issue like this:

Traceback (most recent call last):
  File "WGCNA.py", line 3, in <module>
    pyWGCNA_5xFAD = PyWGCNA.WGCNA(name='5xFAD',
  File "/home/tanygyun/.local/lib/python3.8/site-packages/PyWGCNA/wgcna.py", line 126, in __init__
    super().__init__(species=species, level=level, anndata=anndata, geneExp=geneExp,
  File "/home/tanygyun/.local/lib/python3.8/site-packages/PyWGCNA/geneExp.py", line 69, in __init__
    self.geneExpr = ad.AnnData(X=expressionList, obs=sampleInfo, var=geneInfo)
  File "/home/tanygyun/.local/lib/python3.8/site-packages/anndata/_core/anndata.py", line 291, in __init__
    self._init_as_actual(
  File "/home/tanygyun/.local/lib/python3.8/site-packages/anndata/_core/anndata.py", line 435, in _init_as_actual
    X = ensure_df_homogeneous(X, "X")
  File "/home/tanygyun/.local/lib/python3.8/site-packages/anndata/utils.py", line 139, in ensure_df_homogeneous
    arr = df.sparse.to_coo().tocsr()
  File "/home/tanygyun/.local/lib/python3.8/site-packages/pandas/core/arrays/sparse/accessor.py", line 337, in to_coo
    dtype = find_common_type(self._parent.dtypes.to_list())
  File "/home/tanygyun/.local/lib/python3.8/site-packages/pandas/core/dtypes/cast.py", line 1807, in find_common_type
    raise ValueError("no types given")
ValueError: no types given

**Comment by nargesr** [comment]
@1391794753 can you send me an example of the data you used it?
