### ISSUE TITLE
setuptools >=66 causing error on pip install; package naming convention ('0.23ubuntu1') must be changed

### ISSUE THREAD

**Issue by thirtysix** [mortazavilab/PyWGCNA#23]
I received the following error (below) when installing, both via PyPi and the github clone methods.

I believe it may be related to this noted error, which regards PEP440 enforcement in newer versions of setuptools (>=66):
https://bugs.launchpad.net/ubuntu/+source/distro-info/+bug/1991606

Some discussion on StackOverflow:
[https://stackoverflow.com/questions/75272737/error-invalid-version-0-23ubuntu1-package-distro-info](https://stackoverflow.com/questions/75272737/error-invalid-version-0-23ubuntu1-package-distro-info)

SETUP
Ubuntu: 20.04
Python: 3.8.10
setuptools: 67.4.0 (latest at this time; released Feb 21, 2023)

`ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 357, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 293, in _get_abstract_dist_for
    req.check_if_exists(self.use_user_site)
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 443, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(str(no_marker))
  File "/home/username/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 514, in get_distribution
    dist = get_provider(dist)
  File "/home/username/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 386, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/username/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 956, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/username/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 815, in resolve
    dist = self._resolve_dist(
  File "/home/username/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 844, in _resolve_dist
    env = Environment(self.entries)
  File "/home/username/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1044, in __init__
    self.scan(search_path)
  File "/home/username/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in scan
    self.add(dist)
  File "/home/username/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1096, in add
    dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
  File "/home/username/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2640, in hashcmp
    self.parsed_version,
  File "/home/username/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2694, in parsed_version
    raise packaging.version.InvalidVersion(f"{str(ex)} {info}") from None
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '0.23ubuntu1' (package: distro-info)
`

**Comment by nargesr** [comment]
Hi @thirtysix,

Thank you for reporting this. I updated the setup.py to fix your problem. 
please install the new version (1.16.5) and let me know if you have any questions
